name: Linting and Formatting

on:
  push:
    branches:
      - "*"
    paths:
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/lint-format.yml'

jobs:
  checkout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

  build:
    needs: [checkout]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Linting
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    needs: [checkout, build]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Formatting
        run: npm run format