name: Run unit and E2E tests

on:
  push:
    branches:
      - "*"
    paths:
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/linting.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Installing development dependencies
        run: npm install

      - name: Running unit tests
        run: npm test

      - name: Running  2e tests
        run: npm test:e2e